# Generated by Django 5.2.4 on 2025-08-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalSalesAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcing_manager', models.CharField(blank=True, max_length=100)),
                ('sales_manager', models.CharField(blank=True, max_length=100)),
                ('customer_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('family', 'Family')], max_length=10)),
                ('facilitated_by_pre_sales', models.BooleanField(default=False)),
                ('executive_name', models.CharField(blank=True, max_length=100)),
                ('lead_classification', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], max_length=10)),
                ('customer_classification', models.CharField(blank=True, choices=[('nth', 'NTH'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=10)),
                ('reason_for_closed', models.CharField(blank=True, choices=[('low_budget', 'Low Budget'), ('ready_buyers', 'Ready Buyers'), ('product_related', 'Product related'), ('loan_related', 'Loan related'), ('vasttu', 'Vasttu'), ('location_related', 'Location related'), ('lack_of_inventory', 'Lack of inventory'), ('others', 'Others')], max_length=20)),
                ('current_residence_config', models.CharField(blank=True, choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('plot', 'Plot')], max_length=10)),
                ('current_residence_ownership', models.CharField(blank=True, choices=[('owned', 'Owned'), ('self_owned', 'Self-Owned'), ('rented', 'Rented')], max_length=15)),
                ('family_size', models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('>6', '>6')], max_length=5)),
                ('desired_flat_area', models.CharField(blank=True, help_text='Area of flat customer is looking for', max_length=100)),
                ('source_of_funding', models.CharField(blank=True, choices=[('self_funding', 'Self-Funding'), ('current_property_sale', 'Current Property Sale'), ('loan', 'Loan')], max_length=25)),
                ('ethnicity', models.CharField(blank=True, choices=[('marwadi', 'Marwadi'), ('gujarati', 'Gujarati'), ('maharashtrian', 'Maharashtrian'), ('bengali', 'Bengali'), ('christian', 'Christian'), ('muslim', 'Muslim'), ('parsi', 'Parsi'), ('jain', 'Jain'), ('sindhi', 'Sindhi'), ('others', 'Others')], max_length=15)),
                ('other_projects_considered', models.TextField(blank=True, help_text='Other Projects Considered By The Customer')),
                ('sales_manager_remarks', models.TextField(blank=True, help_text='Sales Manager Remarks About Customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_assessment', to='customer_enquiry.customer')),
            ],
            options={
                'verbose_name': 'Internal Sales Assessment',
                'verbose_name_plural': 'Internal Sales Assessments',
                'db_table': 'internal_sales_assessments',
            },
        ),
    ]
