# Generated by Django 5.2.4 on 2025-08-07 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0002_internalsalesassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Project Name', max_length=200)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('flat_number', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('rera_carpet_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exclusive_deck_balcony', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_parking_count', models.IntegerField(default=0)),
                ('total_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_purchase_price_words', models.TextField(blank=True)),
                ('self_financed', models.BooleanField(default=False)),
                ('housing_loan', models.BooleanField(default=False)),
                ('source_direct', models.BooleanField(default=False)),
                ('source_direct_specify', models.CharField(blank=True, max_length=200)),
                ('referral_customer_name', models.CharField(blank=True, max_length=100)),
                ('referral_project', models.CharField(blank=True, max_length=100)),
                ('referral_flat_no', models.CharField(blank=True, max_length=50)),
                ('application_money_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('application_money_words', models.CharField(blank=True, max_length=500)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gst_words', models.CharField(blank=True, max_length=500)),
                ('cheque_dd_no', models.CharField(blank=True, max_length=100)),
                ('instrument_date', models.DateField(blank=True, null=True)),
                ('drawn_on', models.CharField(blank=True, max_length=200)),
                ('gst_cheque_dd_no', models.CharField(blank=True, max_length=100)),
                ('gst_instrument_date', models.DateField(blank=True, null=True)),
                ('gst_drawn_on', models.CharField(blank=True, max_length=200)),
                ('sales_manager_name', models.CharField(blank=True, max_length=100)),
                ('sourcing_manager_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_applications', to='customer_enquiry.customer')),
            ],
            options={
                'verbose_name': 'Booking Application',
                'verbose_name_plural': 'Booking Applications',
                'db_table': 'booking_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingChannelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('maharera_registration', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('booking_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_partner', to='customer_enquiry.bookingapplication')),
            ],
            options={
                'verbose_name': 'Booking Channel Partner',
                'verbose_name_plural': 'Booking Channel Partners',
                'db_table': 'booking_channel_partners',
            },
        ),
        migrations.CreateModel(
            name='BookingApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_order', models.IntegerField()),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.')], max_length=5)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('other', 'Other')], max_length=15)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('pan_no', models.CharField(blank=True, max_length=10)),
                ('aadhar_no', models.CharField(blank=True, max_length=12)),
                ('residential_status', models.CharField(blank=True, choices=[('indian', 'Indian'), ('nri', 'NRI'), ('pio', 'PIO'), ('oci', 'OCI')], max_length=15)),
                ('residential_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=6)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('correspondence_address', models.TextField(blank=True)),
                ('contact_residence', models.CharField(blank=True, max_length=15)),
                ('contact_office', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('employment_type', models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed')], max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('booking_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='customer_enquiry.bookingapplication')),
            ],
            options={
                'verbose_name': 'Booking Applicant',
                'verbose_name_plural': 'Booking Applicants',
                'db_table': 'booking_applicants',
                'ordering': ['applicant_order'],
                'unique_together': {('booking_application', 'applicant_order')},
            },
        ),
    ]
