# Generated by Django 5.2.4 on 2025-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0004_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], help_text='Marital status of the customer', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender/Sex of the customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='budget',
            field=models.CharField(choices=[('less_than_1cr', 'Less than 1 Cr.'), ('1cr_to_2cr', '1 Cr. to 2 Cr.'), ('2cr_to_4cr', '2 Cr. to 4 Cr.'), ('4cr_to_6cr', '4 Cr. to 6 Cr.'), ('more_than_6cr', 'More than 6 Cr.')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='configuration',
            field=models.CharField(choices=[('1bhk', '1 BHK'), ('1.5bhk', '1.5 BHK'), ('2bhk', '2 BHK'), ('2.5bhk', '2.5 BHK'), ('3bhk', '3 BHK'), ('3.5bhk', '3.5 BHK'), ('4bhk', '4 BHK'), ('duplex', 'Duplex'), ('other_config', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='employment_type',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('business', 'Business'), ('professional', 'Professional'), ('retired', 'Retired'), ('homemaker', 'Homemaker'), ('other', 'Other')], max_length=15),
        ),
    ]
