# Generated by Django 5.2.4 on 2025-08-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0005_customer_marital_status_customer_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingapplicant',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingapplicant',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingapplicant',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingapplicant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingapplicant',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingapplicant',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Ms', 'Ms.'), ('Mrs', 'Mrs.')], max_length=5, null=True),
        ),
    ]
