# Generated by Django 5.2.4 on 2025-08-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0006_fix_customer_field_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalsalesassessment',
            name='area_looking',
            field=models.TextField(blank=True, help_text='Type/Area of flat customer is looking for'),
        ),
        migrations.AddField(
            model_name='internalsalesassessment',
            name='plot',
            field=models.CharField(blank=True, help_text='Plot details', max_length=200),
        ),
        migrations.AddField(
            model_name='internalsalesassessment',
            name='reason_for_lost',
            field=models.CharField(blank=True, choices=[('construction_issue', 'Construction Issue'), ('project_issue', 'Project Issue'), ('developer_history', 'Developer History'), ('budget_issue', 'Budget Issue'), ('google_reviews', 'Google Reviews'), ('not_responding', 'Not Responding'), ('booked_with_competition', 'Booked with competition'), ('pricing_issue', 'Pricing issue'), ('rtmi', 'RTMI'), ('csop', 'CSOP'), ('possession_timeline', 'Possession Timeline'), ('no_reason_given', 'No Reason Given'), ('casual_buyer', 'Casual Buyer'), ('postponed_decision', 'Postponed The Decision'), ('needs_time', 'Needs Time'), ('wrong_number', 'Wrong number'), ('inventory_issue', 'Inventory issue'), ('serial_vdnb', 'Serial VDNB'), ('view_issue', 'View issue'), ('plan_dropped', 'Plan Dropped'), ('configuration_issue', 'Configuration Issue'), ('not_interested', 'Not Interested'), ('location_issue', 'Location issue'), ('vastu_issue', 'Vastu Issue'), ('looking_for_commercial', 'Looking For Commercial'), ('channel_partner', 'Channel Partner'), ('competition', 'Competition')], max_length=30),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='current_residence_config',
            field=models.CharField(blank=True, choices=[('1bhk', '1 BHK'), ('1.5bhk', '1.5 BHK'), ('2bhk', '2 BHK'), ('2.5bhk', '2.5 BHK'), ('3bhk', '3 BHK'), ('3.5bhk', '3.5 BHK'), ('4bhk', '4 BHK'), ('duplex', 'Duplex'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='current_residence_ownership',
            field=models.CharField(blank=True, choices=[('family_owned', 'Family Owned'), ('self_owned', 'Self-Owned'), ('rented', 'Rented'), ('pagdi', 'Pagdi')], max_length=15),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='customer_classification',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='desired_flat_area',
            field=models.CharField(blank=True, help_text='Area of flat customer is looking for (Legacy)', max_length=100),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('maharashtrian', 'Maharashtrian'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='family_size',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6+', '>6')], max_length=5),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='lead_classification',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('lost', 'Lost')], max_length=10),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='reason_for_closed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='internalsalesassessment',
            name='source_of_funding',
            field=models.CharField(blank=True, choices=[('self-funding', 'Self-Funding'), ('current-property-sale', 'Current Property Sale'), ('loan', 'Loan')], max_length=25),
        ),
    ]
