# Generated by Django 5.2.4 on 2025-09-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0008_alter_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingapplicant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingapplicant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingapplicant',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingapplicant',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purpose_of_buying',
            field=models.CharField(choices=[('personal_use', 'Personal Use'), ('investment', 'Investment'), ('second_home', 'Second Home'), ('gift', 'Gift'), ('other', 'Other')], max_length=15),
        ),
    ]
