# Generated by Django 5.2.4 on 2025-09-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0009_alter_bookingapplicant_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_logo', models.ImageField(blank=True, help_text='Upload project logo image', null=True, upload_to='project_logos/')),
                ('project_name', models.CharField(help_text='Name of the project (e.g., Altavista, Ornata)', max_length=200)),
                ('site_name', models.CharField(help_text='Site/Location name (e.g., Mumbai, Tardeo)', max_length=200)),
                ('maharera_no', models.CharField(help_text='MahaRERA Registration Number (e.g., P51900053358)', max_length=50)),
                ('company_name', models.CharField(help_text='Builder/Developer company name (e.g., Heston Builders Pvt. Ltd.)', max_length=200)),
                ('project_code', models.CharField(help_text='Short code for the project (e.g., Alt, Orn, Med)', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this project is currently active/available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['project_name'],
            },
        ),
    ]
