# Generated by Django 5.2.4 on 2025-09-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0010_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_code',
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Complete project address'),
        ),
        migrations.AddField(
            model_name='project',
            name='form_number',
            field=models.CharField(blank=True, help_text='Auto-generated form number (e.g., ALT-12345, ORN-67890)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_prefix',
            field=models.CharField(blank=True, default='', help_text='Short alphabetic prefix (e.g., ALT, ORN, MED)', max_length=10),
        ),
    ]
