# Generated by Django 5.2.4 on 2025-09-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0011_remove_project_project_code_project_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_qr_code',
            field=models.ImageField(blank=True, help_text='Upload project QR code image', null=True, upload_to='project_qr_codes/'),
        ),
    ]
