# Generated by Django 5.2.4 on 2026-03-10 07:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0013_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_step',
            field=models.IntegerField(default=0, help_text='Last saved step (0=not started, 1-5=step completed)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='True when customer has submitted the full form'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('gre', 'GRE'), ('sourcing_manager', 'Sourcing Manager'), ('closing_manager', 'Closing Manager')], default='admin', help_text='User role determines dashboard access and permissions', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='10-digit WhatsApp number for OTP password reset', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit WhatsApp number', regex='^\\d{10}$')]),
        ),
        migrations.CreateModel(
            name='AdditionalChannelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('partner_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^\\d{10}$')])),
                ('rera_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_channel_partners', to='customer_enquiry.customer')),
            ],
            options={
                'verbose_name': 'Additional Channel Partner',
                'verbose_name_plural': 'Additional Channel Partners',
                'db_table': 'additional_channel_partners',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('assign', 'Assigned'), ('submit', 'Form Submitted')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('changes', models.TextField(blank=True, help_text='JSON string of field changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('closing_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_assignments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='customer_enquiry.customer')),
                ('sourcing_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Assignment',
                'verbose_name_plural': 'Customer Assignments',
                'db_table': 'customer_assignments',
            },
        ),
        migrations.CreateModel(
            name='CustomerRevisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_revisits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisits', to='customer_enquiry.customer')),
            ],
            options={
                'verbose_name': 'Customer Revisit',
                'verbose_name_plural': 'Customer Revisits',
                'db_table': 'customer_revisits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
