# Generated by Django 5.2.4 on 2026-03-10 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0014_customer_current_step_customer_is_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='budget',
            field=models.CharField(blank=True, choices=[('less_than_1cr', 'Less than 1 Cr.'), ('1cr_to_2cr', '1 Cr. to 2 Cr.'), ('2cr_to_4cr', '2 Cr. to 4 Cr.'), ('4cr_to_6cr', '4 Cr. to 6 Cr.'), ('more_than_6cr', 'More than 6 Cr.')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='configuration',
            field=models.CharField(blank=True, choices=[('1bhk', '1 BHK'), ('1.5bhk', '1.5 BHK'), ('2bhk', '2 BHK'), ('2.5bhk', '2.5 BHK'), ('3bhk', '3 BHK'), ('3.5bhk', '3.5 BHK'), ('4bhk', '4 BHK'), ('duplex', 'Duplex'), ('other_config', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='construction_status',
            field=models.CharField(blank=True, choices=[('under_construction', 'Under Construction (>1 yr)'), ('near_completion', 'Near Completion (<1 yr)'), ('ready_possession', 'Ready Possession')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('business', 'Business'), ('professional', 'Professional'), ('retired', 'Retired'), ('homemaker', 'Homemaker'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, choices=[('indian', 'Indian'), ('nri', 'NRI'), ('pio', 'PIO'), ('oci', 'OCI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purpose_of_buying',
            field=models.CharField(blank=True, choices=[('personal_use', 'Personal Use'), ('investment', 'Investment'), ('second_home', 'Second Home'), ('gift', 'Gift'), ('other', 'Other')], max_length=15),
        ),
    ]
