# Generated by Django 5.2.4 on 2026-07-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0017_channelpartnermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this inquiry belongs to (used for project-scoped access)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customer_enquiry.project'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this Site Head manages (Site Head role only)', related_name='site_heads', to='customer_enquiry.project'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('edit', 'Edited'), ('delete', 'Deleted'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('assign', 'Assigned'), ('submit', 'Form Submitted'), ('assessment', 'Assessment Saved'), ('booking', 'Booking Submitted'), ('export', 'Exported Data'), ('password_reset', 'Password Reset Requested'), ('cp_add', 'CP Added'), ('cp_remove', 'CP Removed'), ('cp_toggle', 'CP Status Toggled'), ('cp_edit', 'CP Edited'), ('status_update', 'Lead Status Updated'), ('reassign', 'Lead Reassigned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('gre', 'GRE'), ('sourcing_manager', 'Sourcing Manager'), ('closing_manager', 'Closing Manager'), ('site_head', 'Site Head')], default='admin', help_text='User role determines dashboard access and permissions', max_length=20),
        ),
    ]
