# Generated by Django 5.2.4 on 2026-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0019_backfill_customer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('gre', 'GRE'), ('sourcing_manager', 'Sourcing Manager'), ('closing_manager', 'Closing Manager'), ('site_head', 'Site Head'), ('digital_form', 'Digital Form')], default='admin', help_text='User role determines dashboard access and permissions', max_length=20),
        ),
    ]
