# Generated by Django 5.2.4 on 2026-10-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiry', '0020_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalchannelpartner',
            name='rera_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('applied', 'Applied')], default='registered', max_length=10),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='rera_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('applied', 'Applied')], default='registered', max_length=10),
        ),
        migrations.AddField(
            model_name='channelpartnermaster',
            name='rera_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('applied', 'Applied')], default='registered', max_length=10),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='rera_number',
            field=models.CharField(blank=True, help_text="Real Estate Regulatory Authority Number (optional while RERA is 'Applied')", max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this user belongs to: visibility scope for Site Head / GRE, project team for Sourcing / Closing Managers', related_name='site_heads', to='customer_enquiry.project'),
        ),
    ]
